export const applicationFormFields = [
  {
    name: "name",
    label: "Name",
    type: "text",
    required: true,
  },
  {
    name: "email",
    label: "Email Address",
    type: "email",
    required: true,
  },
  {
    name: "phone",
    label: "Phone Number",
    type: "text",
    required: false,
  },
  {
    name: "source",
    label: "How did you hear about this opportunity?",
    type: "select",
    required: true,
    options: [
      "LinkedIn",
      "Company Website",
      "Employee Referral",
      "Job Portal",
      "Other",
    ],
  },
  {
    name: "position",
    label: "Select Position Applying For",
    type: "select",
    required: true,
    // इसको careerJobs array से भी dynamic populate कर सकते हो
    options: [
      "Social Media Manager",
      "Business Development Manager",
      "Frontend Developer",
      "UI/UX Designer",
      "HR & Talent Acquisition Specialist",
      "Other",
    ],
  },
  {
    name: "experience",
    label: "Experience",
    type: "select",
    required: true,
    options: [
      "Fresher",
      "0-1 years",
      "1-3 years",
      "3-5 years",
      "5-10 years",
      "10+ years",
    ],
  },
  {
    name: "cv",
    label: "Upload CV",
    type: "file",
    required: true,
    accept: ".pdf,.doc,.docx,.ppt,.pptx",
    maxSizeMB: 1,
  },
  {
    name: "companyName",
    label: "Company Name",
    type: "text",
    required: false,
  },
  {
    name: "currentCTC",
    label: "Current CTC",
    type: "text",
    required: false,
  },
  {
    name: "expectedCTC",
    label: "Expected CTC",
    type: "text",
    required: false,
  },
  {
    name: "noticePeriod",
    label: "Notice Period",
    type: "select",
    required: false,
    options: [
      "Immediate",
      "15 Days",
      "30 Days",
      "60 Days",
      "90 Days",
      "More than 90 Days",
    ],
  },
  {
    name: "location",
    label: "Current Location",
    type: "text",
    required: true,
  },
  {
    name: "message",
    label: "Your Message to Hiring Manager",
    type: "textarea",
    required: false,
  },
//   {
//     name: "captcha",
//     label: "Verify you are human",
//     type: "captcha",
//     required: true,
//   },
];
